### ISSUE TITLE
Не срабатывает шаблон

### ISSUE THREAD

**Issue by zhum** [vadimpilyugin/log_parser#1]
В файле ntp.yml есть строка:
```
  - 'receive: KoD packet from \S+ has inconsistent .* timestamps. Ignoring'
```
Те не менее, строка
```
receive: KoD packet from 93.180.9.5 has inconsistent xmt/org/rec timestamps. Ignoring.
```
не подходит под него в отчёте.

**Comment by vadimpilyugin** [comment]
А вы добавили новый формат лога? Если лог выглядит именно так, как эта строка, то ему нужен свой формат, отличный от Syslog. Я проверил, если записать строку как 
`May 01 00:00:00 servname ntp[5555]: receive: KoD packet from 93.180.9.5 has inconsistent xmt/org/rec timestamps. Ignoring.`
то парсинг проводится успешно, строка распознается как принадлежащая к серверу servname и подходящая под шаблон.

**Comment by zhum** [comment]
Формат-то сислога как раз:
```
Jun 13 09:55:51 vvv ntpd[17607]: receive: KoD packet from 93.180.9.5 has inconsistent xmt/org/rec timestamps.  Ignoring.
```
Поэтому и непонятно...

**Comment by vadimpilyugin** [comment]
После timestamps стоит два пробела, а в шаблоне только один. Если записать шаблон как `- 'receive: KoD packet from \S+ has inconsistent .* timestamps.\s\sIgnoring'`, то все работает

**Comment by zhum** [comment]
Ок!
